version: '3.4'

services:
  gvm:
    image: isaudits/gvm:latest
    hostname: gvm
    container_name: gvm
    ports:
      - "443:9392"
    env_file:
      - ./local.env
    volumes:
      - ./:/config
      - gvm_data:/usr/local/var/lib
      - gvm_db:/var/lib/postgresql/data
    tty: true

volumes:
  gvm_data:
    name: gvm_data
  gvm_db:
    name: gvm_db
